describe('Count from submit',()=>{

    it('attapent with vaild data',async ()=>{
        browser.url('https://www.malangmusic.in/')

        var name = await browser.$('/html/body/div[13]/div/div/div[2]/form/div/div[1]/input')
        await name.scrollIntoView()
        await name.setValue("Manish Pareek")
        await browser.pause(9000)
        let emal = await browser.$('/html/body/div[13]/div/div/div[2]/form/div/div[2]/input')
        await emal.setValue("manish@gmail.com")
        await browser.pause(9000)
        let ph = browser.$('/html/body/div[13]/div/div/div[2]/form/div/div[3]/input')
        await ph.setValue("9079306652")
        await browser.pause(9000)
        let sb = browser.$('/html/body/div[13]/div/div/div[2]/form/div/div[4]/input')
        await sb.setValue("jhagdfuhsdgfvuadjfhgv")
        await browser.pause(9000)
        let date = browser.$('/html/body/div[13]/div/div/div[2]/form/div/div[5]/div/input')
        await date.setValue("25/05/2023")
        await browser.pause(9000)
        let msg = browser.$('/html/body/div[13]/div/div/div[2]/form/div/div[6]/textarea')
        await msg.setValue("jhdaguda iefguidsygh iudfgduidsagb")
        await browser.pause(9000)
        let capt = browser.$('#a')
        let send = browser.$('//*[@id="b"]')
        await send.setValue((await capt.getValue()).toString())
        await browser.pause(9000)
      //  let  sbtn = browser.$('//*[@id="footer_event"]')
       // await sbtn.click()
    })
})